### ISSUE TITLE
Possibility to run with older sqlite

### ISSUE THREAD

**Issue by nwalet** [rianhunter/dbxfs#18]
I see there was an issue running this with an older sqlite, but on Scientific linux 7 (equivalent of Centos/.RHEL) there is no simple way to update to the required version.
Is there a way to run with an older sqlite or will we always run into the "opaque" error quoted in the list of issues?
Niels

**Comment by rianhunter** [comment]
SQLite 3.9.0 was released on  2015-10-14, and Python 3.5 was released on 2015-09-13. I can technically make it work with older SQLite versions but lowering the Python 3.5 requirement would be a lot more work. Do you have Python 3.5?

**Comment by JeffPsycle** [comment]
If I recall there was also an issue with the 2.9.2 version of fuse on CentOS/RHEL causing some issues. We wound up moving to Fedora to get around the SQLite and Fuse issues.

**Comment by nwalet** [comment]
Thanks--I have just realised I can make it work by compiling a separate sqlite3 for dbxfs; we are running with softwarecollections, so yes, I have python 3.5. Will look for fuse 2.9.2 issues though.
Niels

________________________________
Prof. Niels R. Walet                             Phone:  +44(0)1613063693
School of Physics and Astronomy         Mobile: +44(0)7516622121
The University of Manchester                Room 7.7, Schuster Building
Manchester, M13 9PL,  UK
email: Niels.Walet@manchester.ac.uk   twitter: @nwalet
________________________________

**Comment by rianhunter** [comment]
@nwalet for my reference, what version of SQLite does your distro provide?

**Comment by nwalet** [comment]
RHEL7.5/CENTOS7.3/SL7,5 all run 3.7.17

**Comment by nwalet** [comment]
I guess the fuse issue was this one: https://bugs.centos.org/view.php?id=11042
Looks annoying, but no deal breaker.

**Comment by rianhunter** [comment]
Heres a list of features we use and their required SQLite version

* indexes on expressions: 3.9.0  2015-10-14, without it requires a new column, without it dbxfs will use more memory
* deterministic functions: 3.8.3 2014-02-03, without it some queries will be a bit slower (due to repetitive calls to functions)
* shared-cached in-memory databases 3.7.13 2012-06-11, without it temp databases will take up disk space and be a bit slower (due to calls to write() and read()).

I am fine dropping these requirements but I am hesitant to do it given Python 3.5 was released before SQLite 3.9.0 and there are workarounds.

**Comment by rianhunter** [comment]
This is never going to happen
