### ISSUE TITLE
Mount error when passing volume to Docker container

### ISSUE THREAD

**Issue by dseeker** [rianhunter/dbxfs#30]
I've been able to mount a dropbox folder to /media/dropbox/, and I can list it and see in WinSCP.
But strangely I can't see the folder when accessing via FTP, I try to pass the volume as envars for docker run it comes back with a mounting error:

> docker: Error response from daemon: OCI runtime create failed: container_linux.go:348: starting container process caused "process_linux.go:279: applying cgroup configuration for process caused \"mountpoint for devices not found\"": unknown.

This is the docker cmd, it works for other files, including [SSHFS](https://github.com/libfuse/sshfs) fuse mounts
`sudo docker run --rm --device /dev/dri:/dev/dri --entrypoint ffprobe -v /media/dropbox/Team-Ordner/Ingest/:/ingest jrottenberg/ffmpeg:4.1-vaapi -v error -i "/ingest/film/videofile.mov" -print_format json -show_streams -select_streams v`

permission are set to root
![image](https://user-images.githubusercontent.com/11655138/53185069-90464380-35fe-11e9-9fd7-beed75401b97.png)

wondering if you have come across this error and found a fix for it.

PS: testing now I can see no docker commands works anymore.. looks like installing DBXFS has broken docker on this machine :(

**Comment by rianhunter** [comment]
you might want to look more into how FUSE works. most likely you are failing to use `-o allow_other` or `-o allow_root`. if docker is now broken on your machine, it's unlikely dbxfs has broken it since dbxfs does not change any system state outside of using the FUSE kernel driver. more likely docker has a bug around it's state / process management after encountering an error.
